def helpAdmin():
    print("==========HELP==========")
    print("register - melakukan registrasi user baru")
    print("carirarity - mencari gadget dengan rarity tertentu")
    print("caritahun - mencari gadget dengan kategori tahun tertentu. Kategori: =,<,>,<=,>=")
    print("tambah - menambah item baru")
    print("hapus - menghapus item")
    print("ubahjumlah - mengubah jumlah gadget atau consumable")
    print("riwayatpinjam - melihat riwayat peminjaman gadget user")
    print("riwayatkembali - melihat riwayat pengembalian gadget user")
    print("riwayatambil - melihat riwayat pengambilan consumable user")
    print("save - menyimpan data program")
    print("exit - keluar program")
    print()

def helpUser():
    print("==========HELP==========")
    print("carirarity - mencari gadget dengan rarity tertentu")
    print("caritahun - mencari gadget dengan kategori tahun tertentu. Kategori: =,<,>,<=,>=")
    print("pinjam - meminjam gadget dengan jumlah tertentu")
    print("kembalikan - mengembalikkan gadget yang dipinjam")
    print("minta - meminta consumable dengan jumlah tertentu")
    print("save - menyimpan data program")
    print("exit - keluar program")
    print()